const RestaurantData = [
  {
    label: "Chinese Wok",
    rating: "4.2",
    description: "Chinese, Asian, Tibetan, Desserts ",
    location: "Sarjapur Road",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e0839ff574213e6f35b3899ebf1fc597",
  },
  {
    label: "McDonald's",
    rating: "4.4",
    description: "Burgers, Beverages, Cafe ,Desserts ",
    location: "Bellandur",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/9/18/85a06046-ebc9-4f01-b12b-9323e94308c3_23690.jpg",
  },
  {
    label: "Louis Burger",
    rating: "4.2",
    description: "Burgers, American, Fast Food ",
    location: "Sarjapur",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/3dc6b33b30116d30333367ea9127403f",
  },
  {
    label: "Burger King",
    rating: "4.2",
    description: "Burgers, American ",
    location: "Kaikondrahalli",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/55d0daa1-ad2e-4893-be06-4709c5c68d49_72821.JPG",
  },
  {
    label: "Pizza Hut",
    rating: "4.3",
    description: "Pizzas",
    location: "Bellandur",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/7/17/c02ffaab-8fa2-4039-92f4-efe1001f6162_323512.jpg",
  },
  {
    label: "KFC",
    rating: "4.3",
    description: "Burgers, Fast Food, Rolls & Wraps ",
    location: "Mahadevapura",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/aa54ecc4-6ce6-4c9e-a44a-d866414cb9c7_736494.JPG",
  },
  {
    label: "Chaayos Chai+Snacks=Relax",
    rating: "4.5",
    description:
      "Bakery, Beverages, Chaat, Desserts, Home Food, Italian, Maharashtrian, Snacks, Street Food, Sweets ",
    location: "Bellandur",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/dfbcecfc-b380-4648-930a-b9b56b21e781_263484.JPG",
  },
  {
    label: "Momo Zone - The Momo Company",
    rating: "4.2",
    description: "Chinese, Tibetan, Fast Food, Momos",
    location: "Sarjapur Road",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/pinn06puvmxk0tai6ncz",
  },
  {
    label: "No Sugar, Please! -Juices, Salads & Fruit Bowls",
    rating: "4.6",
    description: "Healthy Food, Juices, Salads",
    location: "Bellandur",
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/4/1cb90b5d-9ae4-413c-ad7a-f19f8d7d5992_256913.jpg",
  },
];

const RES_LIST_DATE = {
  data: [
    {
      address: {
        country: "United States",
        fullAddress: "233 8th Ave, New York City, NY 10011-1606",
        latitude: 40.74464,
        longitude: -73.99936,
        postalCode: "10011-1606",
      },
      cuisines: ["French", "Mediterranean"],
      id: 27711676,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d27711676-Reviews-Marsanne-New_York_City_New_York.html",
      menu: "",
      name: "Marsanne",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ab/3e/4e/at-marsanne-nyc-we-re.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ac/e6/eb/pan-seared-scallops.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ac/e6/f0/kitchen-counter.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ac/e6/ea/agnolotti.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ac/e6/ef/bar.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 5,
      reviewsCount: 35,
      telephone: "+1 646-726-4614",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/ab/3e/4e/at-marsanne-nyc-we-re.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "152 W 44th St, New York City, NY 10036",
        latitude: 40.756783,
        longitude: -73.98513,
        postalCode: "10036",
      },
      cuisines: ["American", "Barbecue", "Caucasian"],
      id: 424440,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d424440-Reviews-Virgil_s_Real_Bbq-New_York_City_New_York.html",
      menu: "",
      name: "Virgil's Real Bbq ",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e8/f3/22/ribs-in-the-smoker.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e8/f2/8d/exterior.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e9/0d/1a/dessert-catering.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ad/5e/38/bacon-eggs-cheese-burrito.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ad/5e/37/chef-s-favorite-burrito.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 4928,
      telephone: "+1 212-221-3800",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e8/f3/22/ribs-in-the-smoker.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "28 Liberty Street 60th Floor, New York City, NY 10005",
        latitude: 40.70808,
        longitude: -74.00882,
        postalCode: "10005",
      },
      cuisines: ["American"],
      id: 14416742,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d14416742-Reviews-Manhatta-New_York_City_New_York.html",
      menu: "https://www.manhattarestaurant.com/the-dining-room/",
      name: "Manhatta",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/4f/51/7f/east-facing-view.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/bd/55/c7/dining-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/4f/51/8c/seats-at-the-bar.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/4f/51/88/deep-fake-negroni.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/bd/55/d3/kitchen.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 433,
      telephone: "+1 212-230-5788",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/4f/51/7f/east-facing-view.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "145 W 53rd St, New York City, NY 10019-6005",
        latitude: 40.762756,
        longitude: -73.980644,
        postalCode: "10019-6005",
      },
      cuisines: ["French", "Steakhouse"],
      id: 21410713,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d21410713-Reviews-La_Grande_Boucherie-New_York_City_New_York.html",
      menu: "https://www.boucherieus.com/la-grande-boucherie-menus/",
      name: "La Grande Boucherie",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/bc/76/0d/la-grande-boucherie-joie.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/5b/f0/67/gallery.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/5b/f0/66/la-grande-boucherie.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/6d/13/e6/lgb.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/6d/13/e5/lgb.jpg",
      ],
      priceTypes: "$$$$",
      rating: 5,
      reviewsCount: 2588,
      telephone: "+1 212-510-7714",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/bc/76/0d/la-grande-boucherie-joie.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "200 W 44th St. Times Square, New York City, NY 10036",
        latitude: 40.7575,
        longitude: -73.98666,
        postalCode: "10036",
      },
      cuisines: ["Italian"],
      id: 12947829,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d12947829-Reviews-Carmine_s-New_York_City_New_York.html",
      menu: "https://www.carminesnyc.com/menus/upper-west-side-dining",
      name: "Carmine's",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ac/fa/27/host-your-next-event.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/be/51/eb/dining.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/c8/26/20/upstairs-dining-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/be/51/dc/meatballs.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ac/fa/2e/celebrate-with-carmines.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 13243,
      telephone: "+1 212-221-3800",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/ac/fa/27/host-your-next-event.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "228 W 52nd St, New York City, NY 10019-5802",
        latitude: 40.762848,
        longitude: -73.98386,
        postalCode: "10019-5802",
      },
      cuisines: ["Steakhouse", "Seafood"],
      id: 478965,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d478965-Reviews-Gallaghers_Steakhouse-New_York_City_New_York.html",
      menu: "https://www.gallaghersnysteakhouse.com/menu.php",
      name: "Gallaghers Steakhouse",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/23/e7/a4/gallaghers-new-york-steakhouse.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/5f/18/46/gallagher-s-steak-house.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/5f/18/3f/gallagher-s-steak-house.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/5f/18/2f/gallagher-s-steak-house.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/5f/18/28/gallagher-s-steak-house.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 6059,
      telephone: "+1 212-586-5000",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/23/e7/a4/gallaghers-new-york-steakhouse.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "90 E 42nd St, New York City, NY 10017-5409",
        latitude: 40.75197,
        longitude: -73.97778,
        postalCode: "10017-5409",
      },
      cuisines: ["American"],
      id: 502744,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d502744-Reviews-Pershing_Square_Restaurant-New_York_City_New_York.html",
      menu: "https://pershingsquare.com/dinner/",
      name: "Pershing Square Restaurant",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/4f/0e/ef/restaurant-near-me-new.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/38/d4/fa/homemade-apple-pie.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/15/98/12/brunch-in-midtown-nyc.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/23/c4/ef/breakfast.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/15/97/fe/cappuccino-and-a-muffin.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 2679,
      telephone: "+1 212-286-9600",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/4f/0e/ef/restaurant-near-me-new.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "33 Cortlandt Alley, New York City, NY 10013",
        latitude: 40.718124,
        longitude: -74.001915,
        postalCode: "10013",
      },
      cuisines: ["American"],
      id: 16713744,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d16713744-Reviews-Au_Cheval-New_York_City_New_York.html",
      menu: "",
      name: "Au Cheval",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/80/d1/our-space.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/82/68/beautiful-cocktails.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/82/0b/old-fashioned.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/81/ed/fried-bologna-sandwich.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/81/a2/crafted-beer.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 125,
      telephone: "+1 646-350-2429",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b8/80/d1/our-space.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "75 9th Ave Chelsea Market, New York City, NY 10011-7006",
        latitude: 40.742554,
        longitude: -74.00605,
        postalCode: "10011-7006",
      },
      cuisines: ["Seafood", "Healthy"],
      id: 2076999,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d2076999-Reviews-Lobster_Place-New_York_City_New_York.html",
      menu: "https://www.lobsterplace.com/menus/",
      name: "Lobster Place",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/fe/86/fresh-scallops-shrimp.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/fe/6e/fresh-steamed-lobster.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/fd/d9/sake-uni-ikura-don.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/ff/e9/the-sushi-bar-expereince.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/fe/c1/sushi-tasting-platter.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 2347,
      telephone: "+1 212-255-5672",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/e4/fe/86/fresh-scallops-shrimp.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "125 Mulberry Street, New York City, NY 10013-4603",
        latitude: 40.717915,
        longitude: -73.99819,
        postalCode: "10013-4603",
      },
      cuisines: ["Italian"],
      id: 424422,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d424422-Reviews-Il_Cortile_Restaurant-New_York_City_New_York.html",
      menu: "",
      name: "Il Cortile Restaurant",
      openStatus: "CLOSED",
      openStatusText: "Closed today",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/14/d3/c9/the-il-cortile-courtyard.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/b3/1b/9f/calamari.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/b3/1b/9e/filet-di-manzo.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/b3/1b/9a/mussels-and-clams.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/b3/1b/99/outdoor-dining-room.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 960,
      telephone: "+1 212-226-6060",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/14/d3/c9/the-il-cortile-courtyard.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "220 W 49th St, New York City, NY 10019-7562",
        latitude: 40.761017,
        longitude: -73.98528,
        postalCode: "10019-7562",
      },
      cuisines: ["Italian"],
      id: 558217,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d558217-Reviews-Da_Marino_Restaurant-New_York_City_New_York.html",
      menu: "https://www.toasttab.com/da-marino-nyc-220w-49th-street",
      name: "Da Marino Restaurant",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cb/69/filename-img-20120430.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cc/20/filename-ronnie-wood.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cc/01/filename-kevin-spacey.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cb/e6/filename-chris-noth-lady.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cb/d6/filename-img-3844-wm.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 2917,
      telephone: "+1 212-541-6601",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/8e/cb/69/filename-img-20120430.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "236 5th Ave Between 27th \u0026 28th Street, New York City, NY 10001-7606",
        latitude: 40.74442,
        longitude: -73.9877,
        postalCode: "10001-7606",
      },
      cuisines: ["Lebanese", "Mediterranean", "Middle Eastern"],
      id: 812082,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d812082-Reviews-Ilili_Restaurant_Nyc-New_York_City_New_York.html",
      menu: "https://www.ililirestaurants.com/ilili-nyc-menu/",
      name: "Ilili Restaurant Nyc",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/02/66/83/1e/ilili.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/66/83/20/ilili.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/3f/c5/28/interior-photo-of-ilili.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/3f/c5/27/dining-room-of-lili-restaurant.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/3f/c5/26/ilili-restaurant-nyc.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 1248,
      telephone: "+1 212-683-2929",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/02/66/83/1e/ilili.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "714 Seventh Avenue Two Times Square at W. 48th Street, New York City, NY 10036-7301",
        latitude: 40.75962,
        longitude: -73.98468,
        postalCode: "10036-7301",
      },
      cuisines: ["Contemporary"],
      id: 1923765,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d1923765-Reviews-R_Lounge-New_York_City_New_York.html",
      menu: "",
      name: "R Lounge",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/05/26/11/enjoy-a-quintessential.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/18/ef/6e/rlounge.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/18/ef/6f/r-lounge.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/83/3a/42/r-lounge-seating.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/05/26/1c/relax-over-a-fine-meal.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 619,
      telephone: "+1 212-261-5114",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/05/26/11/enjoy-a-quintessential.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "20 W 64th St One Lincoln Plaza, New York City, NY 10023-7129",
        latitude: 40.77179,
        longitude: -73.981445,
        postalCode: "10023-7129",
      },
      cuisines: ["Mediterranean", "Healthy"],
      id: 2242032,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d2242032-Reviews-Boulud_Sud-New_York_City_New_York.html",
      menu: "https://www.bouludsud.com/nyc/menus/#dinner",
      name: "Boulud Sud",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/a5/ac/29/boulud-sud.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/7d/33/ed/lunch-at-boulud-sud.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/7d/33/ec/brunch-at-boulud-sud.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/7d/33/eb/brunch-at-boulud-sud.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/7d/06/1a/brunch-at-boulud-sud.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 937,
      telephone: "+1 212-595-1313",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/a5/ac/29/boulud-sud.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "240 East 58th Street, New York City, NY 10022-2001",
        latitude: 40.760056,
        longitude: -73.96558,
        postalCode: "10022-2001",
      },
      cuisines: ["Steakhouse", "Seafood"],
      id: 1236281,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d1236281-Reviews-Club_A_Steakhouse-New_York_City_New_York.html",
      menu: "http://www.clubasteakhouse.com/menu/",
      name: "Club A Steakhouse",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/d3/02/cc/photo2jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/5f/58/3c/porter-house-for-2.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/5f/57/c3/dining-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/5f/57/63/wine-cellar.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/6e/b8/a0/caption.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 4615,
      telephone: "+1 212-688-4190",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/d3/02/cc/photo2jpg.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "1900 Broadway, New York City, NY 10023-7001",
        latitude: 40.771698,
        longitude: -73.98183,
        postalCode: "10023-7001",
      },
      cuisines: ["Italian"],
      id: 425554,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d425554-Reviews-Cafe_Fiorello-New_York_City_New_York.html",
      menu: "",
      name: "Cafe Fiorello",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/5c/55/f1/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/c8/98/f2/cafe-fiorello.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/64/c7/85/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/64/c7/84/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/50/36/77/caption.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 1431,
      telephone: "+1 212-595-5330",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/5c/55/f1/caption.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "1150 Broadway Between 26th And 27th Streets, New York City, NY 10001-7704",
        latitude: 40.744244,
        longitude: -73.98861,
        postalCode: "10001-7704",
      },
      cuisines: ["American", "Bar", "Fusion"],
      id: 1460354,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d1460354-Reviews-230_Fifth_Rooftop_Bar-New_York_City_New_York.html",
      menu: "https://www.230-fifth.com/food-menu/",
      name: "230 Fifth Rooftop Bar",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/86/c1/85/deck-seating.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/86/c1/9f/drone-on-broadway.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/86/c1/7d/new-years-eve.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/86/c1/8b/drone-overhead.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/3f/18/c1/our-winter-igloos-are.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 4099,
      telephone: "+1 212-725-4300",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/86/c1/85/deck-seating.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "440 W 33rd St Between 9th/10th Avenues, New York City, NY 10001-2601",
        latitude: 40.753296,
        longitude: -73.99881,
        postalCode: "10001-2601",
      },
      cuisines: ["Bar", "Pub", "Middle Eastern"],
      id: 23636199,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d23636199-Reviews-Zou_Zou_s-New_York_City_New_York.html",
      menu: "",
      name: "Zou Zou's",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/36/57/e4/banquettes.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/e7/d9/ea/dips.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/36/57/0a/dining-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/cc/fa/9d/golden-beet-salad-with.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/cc/fa/a7/shareable-steak.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4,
      reviewsCount: 40,
      telephone: "+1 212-380-8585",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/36/57/e4/banquettes.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "200 W 39th St 30th Floor, New York City, NY 10018-8242",
        latitude: 40.75419,
        longitude: -73.98885,
        postalCode: "10018-8242",
      },
      cuisines: ["American", "Bar"],
      id: 6767627,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d6767627-Reviews-The_Skylark_Rooftop_Bar-New_York_City_New_York.html",
      menu: "https://www.theskylarknyc.com/lounge/menus/signature-cocktails",
      name: "The Skylark - Rooftop Bar",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/f4/20/d5/outdoor-roof-top-bar.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/cc/c9/4b/extraordinary-sunset.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/79/3f/8c/cheese-charcuterie.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/a7/5f/9f/main-lounge-theskylarknyc.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/a7/5e/38/cozy-up-on-the-main-lounge.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 393,
      telephone: "+1 212-257-4577",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/f4/20/d5/outdoor-roof-top-bar.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "35 E 76th St, New York City, NY 10075",
        latitude: 40.774475,
        longitude: -73.9632,
        postalCode: "10075",
      },
      cuisines: ["American", "Bar"],
      id: 1143073,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d1143073-Reviews-Bemelmans_Bar-New_York_City_New_York.html",
      menu: "https://www.rosewoodhotels.com/content/dam/rosewoodhotels/property/the-carlyle-new-york/en/documents/dining/bemelmans-bar/Bemelmans%2520Bar.pdf",
      name: "Bemelmans Bar",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/be/55/72/bemelmans-bar.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/60/ed/1c/bar-we-were-at-a-table.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/0b/65/cb/photo1jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/f7/5b/8a/cosy-bemelmans-bar-in.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/3a/50/40/even-on-the-lampshades.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 519,
      telephone: "+1 212-744-1600",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/be/55/72/bemelmans-bar.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "30 Hudson Yards 101st Floor, New York City, NY 10001-2170",
        latitude: 40.753998,
        longitude: -74.001076,
        postalCode: "10001-2170",
      },
      cuisines: ["American"],
      id: 20343929,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d20343929-Reviews-Peak_Restaurant_Bar-New_York_City_New_York.html",
      menu: "https://www.peaknyc.com/menus/",
      name: "Peak Restaurant \u0026 Bar",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/74/a5/5d/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/5c/34/37/starter.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/5c/34/20/main.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/5c/34/1b/starters.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/5c/34/17/cheesecake-fig-almond.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 214,
      telephone: "+1 332-204-8547",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/74/a5/5d/caption.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "72 West 36th Street, New York City, NY 10018-8025",
        latitude: 40.750755,
        longitude: -73.98648,
        postalCode: "10018-8025",
      },
      cuisines: ["American", "Steakhouse"],
      id: 425330,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d425330-Reviews-Keens_Steakhouse-New_York_City_New_York.html",
      menu: "",
      name: "Keens Steakhouse",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/a0/72/00/photo0jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/99/24/6b/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/99/24/6a/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/99/24/69/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/99/24/68/caption.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 6943,
      telephone: "+1 212-947-3636",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/a0/72/00/photo0jpg.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "75 Thompson St., New York City, NY 10012",
        latitude: 40.724686,
        longitude: -74.00318,
        postalCode: "10012",
      },
      cuisines: ["Italian", "Pizza", "Sicilian"],
      id: 12425739,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d12425739-Reviews-Piccola_Cucina_Estiatorio-New_York_City_New_York.html",
      menu: "http://www.piccolacucinagroup.com/wp-content/uploads/2018/06/Menu-Estiatorio-2018-compressed.pdf",
      name: "Piccola Cucina Estiatorio",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/9f/fd/63/piccola-cucina-estiatorio.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a0/00/54/maccheroni-alla-norma.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a0/00/4c/grilled-shrimp.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a0/00/40/paccheri-lobster.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a0/00/3a/cassata-siciliana.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 5,
      reviewsCount: 954,
      telephone: "+1 646-781-9183",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/9f/fd/63/piccola-cucina-estiatorio.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "30 Rockefeller Plz 65th Floor, New York City, NY 10112-0015",
        latitude: 40.75908,
        longitude: -73.97945,
        postalCode: "10112-0015",
      },
      cuisines: ["American", "Contemporary"],
      id: 7260260,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d7260260-Reviews-Rainbow_Room-New_York_City_New_York.html",
      menu: "",
      name: "Rainbow Room",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/42/2e/03/rainbow-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/92/16/41/photo4jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/ff/f5/1e/my-main-course-sea-bass.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/48/ad/f1/photo0jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/6c/9a/3b/rainbow-room.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 701,
      telephone: "+1 212-632-5000",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/42/2e/03/rainbow-room.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "1 Hanover Square, New York City, NY 10004",
        latitude: 40.704636,
        longitude: -74.00965,
        postalCode: "10004",
      },
      cuisines: ["American", "Steakhouse"],
      id: 1175842,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d1175842-Reviews-Harry_s-New_York_City_New_York.html",
      menu: "https://www.harrysnyc.com/menus/",
      name: "Harry's",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e8/97/bd/main-room-at-harry-s.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e3/20/59/one-of-our-delicious.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/25/a9/4f/for-a-more-intimate-group.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/25/a9/4a/dine-or-host-an-event.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/25/a9/43/harry-s-is-well-known.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 386,
      telephone: "+1 212-785-9200",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e8/97/bd/main-room-at-harry-s.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "10 East 52nd Street, New York City, NY 10022",
        latitude: 40.7594,
        longitude: -73.975586,
        postalCode: "10022",
      },
      cuisines: ["French", "Mediterranean", "European"],
      id: 810307,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d810307-Reviews-FIG_OLIVE-New_York_City_New_York.html",
      menu: "",
      name: "FIG \u0026 OLIVE",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/cf/9e/30/glasses-on-a-table.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/6a/7f/8e/fig-olive-fifth-avenue.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/d1/c3/a1/branzino.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/cf/9e/33/second-floor.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/cf/9e/32/second-floor.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4,
      reviewsCount: 2688,
      telephone: "+1 212-319-2002",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/cf/9e/30/glasses-on-a-table.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "807 8th Avenue, New York City, NY 10019-7418",
        latitude: 40.761555,
        longitude: -73.986855,
        postalCode: "10019-7418",
      },
      cuisines: ["American", "Diner"],
      id: 6892205,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d6892205-Reviews-Times_Square_Diner-New_York_City_New_York.html",
      menu: "https://ordertimessquarediner.com/menu",
      name: "Times Square Diner",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/8a/f4/69/me-encanto-crispy-chicken.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/92/65/caption.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/aa/e3/51/i-receive-a-great-breakfast.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/4c/00/c8/times-square-diner.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/8d/80/ef/bbq-bacon-burger-bbq.jpg",
      ],
      priceTypes: "$",
      rating: 4.5,
      reviewsCount: 2506,
      telephone: "+1 212-315-2400",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/8a/f4/69/me-encanto-crispy-chicken.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "1250 Broadway 39th Floor, New York City, NY 10001-3701",
        latitude: 40.74769,
        longitude: -73.98788,
        postalCode: "10001-3701",
      },
      cuisines: ["Bar", "Barbecue", "Korean"],
      id: 3373343,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d3373343-Reviews-Gaonnuri-New_York_City_New_York.html",
      menu: "http://www.GAONNURINYC.com/menu",
      name: "Gaonnuri",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/01/1f/5b/gaonnuri.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3e/d7/12/korean-bbq-with-a-view.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/c7/36/f2/gaonnuri.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3e/d8/d9/traditional-korean-bbq.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/3e/d8/87/korean-bbq-with-a-view.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 645,
      telephone: "+1 212-971-9045",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/01/1f/5b/gaonnuri.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "510 Broome St, New York City, NY 10013-1695",
        latitude: 40.72354,
        longitude: -74.00317,
        postalCode: "10013-1695",
      },
      cuisines: ["Italian", "Wine Bar"],
      id: 814362,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d814362-Reviews-Aurora_SoHo-New_York_City_New_York.html",
      menu: "",
      name: "Aurora SoHo",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/2b/e1/1e/photo1jpg.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/ed/e1/61/aurora-soho.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/49/e7/c6/aurora-soho.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/62/17/f6/aurora-soho_rotated_90.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/46/33/36/sala-principale.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 414,
      telephone: "+1 212-334-9020",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/2b/e1/1e/photo1jpg.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress:
          "143 E 49th St Between Lexington and third AV, New York City, NY 10017",
        latitude: 40.75575,
        longitude: -73.97215,
        postalCode: "10017",
      },
      cuisines: ["Italian"],
      id: 10083109,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d10083109-Reviews-Toscana_49-New_York_City_New_York.html",
      menu: "",
      name: "Toscana 49",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/54/f3/0b/toscana49.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/63/14/b7/matteo-berrettini-in.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/62/f7/03/sunday-night-in-toscana.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/37/92/aa/toscana49.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/06/11/1d/toscana49.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 790,
      telephone: "+1 212-256-0190",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/54/f3/0b/toscana49.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "249 W 49th St, New York City, NY 10019-7404",
        latitude: 40.761612,
        longitude: -73.98595,
        postalCode: "10019-7404",
      },
      cuisines: ["American", "Bar", "Gastropub"],
      id: 3220843,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d3220843-Reviews-Lillie_s_Victorian_Establishment-New_York_City_New_York.html",
      menu: "https://www.lilliesnyc.com/menu-1",
      name: "Lillie's Victorian Establishment",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/ad/bridgerton-inspired-theme.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/b1/lillie-langtry-mosaic.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/b0/main-bar.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/af/bridgerton-inspired-theme.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/ae/the-only-fans-martini.jpg",
      ],
      priceTypes: "$$ - $$$",
      rating: 4.5,
      reviewsCount: 1304,
      telephone: "+1 212-957-4530",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/79/73/ad/bridgerton-inspired-theme.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "56 Beaver St Frnt A, New York City, NY 10004-2436",
        latitude: 40.705074,
        longitude: -74.010185,
        postalCode: "10004-2436",
      },
      cuisines: ["American", "Steakhouse"],
      id: 459628,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d459628-Reviews-Delmonico_s-New_York_City_New_York.html",
      menu: "https://www.theoriginaldelmonicos.com/",
      name: "Delmonico's",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/04/11/cd/delmonico-s-refreshed.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/04/17/31/delmonico-s.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/04/17/a5/delmonico-s.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/04/16/f7/delmonico-s.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/04/11/cf/delmonico-steak.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 1049,
      telephone: "+1 212-381-1237",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/04/11/cd/delmonico-s-refreshed.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "1 E 35th Street, New York City, NY 10016-3828",
        latitude: 40.748985,
        longitude: -73.98342,
        postalCode: "10016-3828",
      },
      cuisines: ["Steakhouse"],
      id: 12015308,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d12015308-Reviews-Royal_35_Steakhouse-New_York_City_New_York.html",
      menu: "https://royal35steakhouse.com/menus#dinner",
      name: "Royal 35 Steakhouse",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e2/90/ef/usda-prime-dry-aged-porterhous.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/31/04/c5/main-dining-room.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e2/91/0c/usda-prime-dry-aged-bone.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e2/90/e0/filet-mignon.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e2/91/18/chilean-sea-bass-fish.jpg",
      ],
      priceTypes: "$$$$",
      rating: 4.5,
      reviewsCount: 636,
      telephone: "+1 212-804-7276",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e2/90/ef/usda-prime-dry-aged-porterhous.jpg",
    },
    {
      address: {
        country: "United States",
        fullAddress: "412 Amsterdam Avenue, New York City, NY 10024",
        latitude: 40.78373,
        longitude: -73.978294,
        postalCode: "10024",
      },
      cuisines: ["American", "Fast Food", "Deli", "Healthy"],
      id: 26586785,
      link: "https://www.tripadvisor.com/Restaurant_Review-g60763-d26586785-Reviews-Sandwell-New_York_City_New_York.html",
      menu: "https://www.getsandwell.com/menu",
      name: "Sandwell",
      openStatus: "CLOSED",
      openStatusText: "Closed now",
      photos: [
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5e/a6/turkey-meatball-sub.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5e/c8/cacio-e-pepe-mushroom.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5f/48/lunchbox-special.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5f/1c/mac-cheese-peas.jpg",
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5f/11/iced-coffee.jpg",
      ],
      priceTypes: "$",
      rating: 5,
      reviewsCount: 8,
      telephone: "+1 212-321-7911",
      thumbnail:
        "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/83/5e/a6/turkey-meatball-sub.jpg",
    },
  ],
  pageInfo: {
    endCursor: "60763|30",
    hasNextPage: true,
  },
};

export { RestaurantData, RES_LIST_DATE };
